name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false
  REGISTRY: ghcr.io

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'WEHI-SODA-Hub/spatialvpt') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Download test data
        run: |
          cd ${GITHUB_WORKSPACE}

          mkdir -p data/minimal/images
          wget -O data/minimal/images/mosaic_DAPI_z3.tif https://github.com/nf-core/test-datasets/raw/modules/data/imaging/segmentation/nuclear_image.tif
          cp data/minimal/images/mosaic_DAPI_z3.tif data/minimal/images/mosaic_PolyT_z3.tif

          # Get config file
          wget -O data/minimal/cellpose2_nuclei.json https://raw.githubusercontent.com/Vizgen/vpt-plugin-cellpose2/refs/heads/develop/example_analysis_algorithm/cellpose2_nuclei.json

          # Create a dummy micron to mosaic pixel transform file
          echo "2 0 0" > data/minimal/images/micron_to_mosaic_pixel_transform.csv
          echo "0 2 0" >> data/minimal/images/micron_to_mosaic_pixel_transform.csv
          echo "0 0 1" >> data/minimal/images/micron_to_mosaic_pixel_transform.csv

          # Create a dummy detected transcripts CSV file
          echo ",barcode_id,global_x,global_y,global_z,x,y,fov,gene,transcript_id" > data/minimal/detected_transcripts.csv
          echo "101,10,370.95007,5.520504,0.0,611.833,110.285774,0,GAPDH,ENST00000542121.2" >> data/minimal/detected_transcripts.csv
          echo "102,10,355.46716,6.4616404,0.0,668.4725,119.0,0,GAPDH,ENST00000542121.2" >> data/minimal/detected_transcripts.csv

      - name: Log into Container registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results
